### ISSUE TITLE
Предложения по улучшению мода

### ISSUE THREAD

**Issue by Darek505** [TheVitya2127/Nuclear-Furniture-Old#1]
1.1: Раскомментировать `disableSpotless = true` и `disableCheckstyle = true` в gradle.properties: эти вещи нужны исключительно в проектах gtnh для проверки отступов и т.п. Тут они не нужны.

1.2: Ручной контроль версий: в build.gradle нужно написать `version = "0.0.0"` и поставить нужную версию. В gtnh build script контроль версий осуществляется через git и github workflows. Тоже самое, здесь это не нужно.

2.1: Конфликт с вкладкой блоков ntm:

Nuclear-Furniture:
```java
    public static CreativeTabs blocksTab = new BlocksTab(CreativeTabs.getNextID(), "tabBlocks");
```
    
Hbm-s-Nuclear-Tech:

```java
	public static CreativeTabs blockTab = new BlockTab(CreativeTabs.getNextID(), "tabBlocks");					// ore and mineral blocks
```

они одинаковые, понятно что будет конфликт. Решением будет поменять ключ вкладки (это что второе - "tabBlocks") на что-нибудь другое. Например `"tabBlocksNF"`, а также поменять ключ перевода на соответствующий в .lang файлах:

`NuclearFurniture.java`
```java
    public static CreativeTabs blocksTab = new BlocksTab(CreativeTabs.getNextID(), "tabBlocksNF");
```
`en_US.lang`
```
itemGroup.tabBlocksNF=NF Deco Blocks
```

Вроде все, удачи в создании!

**Comment by Ruslanllll** [comment]
1.1: А чем проверка стиля кода мешает? Ну типо - это очень удобно в некоторых ситуациях

**Comment by Darek505** [comment]
На данный момент мод не собирается если они включены. Не исключаю что можно сделать все нормально, но мне кажется это лишняя трата времени
